@startuml Join a Trip

title Join a Trip
actor Passenger as a
participant View as v
participant Service as s
participant "Data Access" as da
database Database as db

activate a
a -> v : Show all trips
activate v
v --> a : trips available
a -> v: join a trip
v -> s: bookaTrip()
alt "available seats"
activate s
s -> da: send Booking model
activate da
da -> db: Add model to database
activate db
db --> da: Model added
deactivate db
da --> s : booking added
deactivate da
s --> v : trip booked
v --> a: Show confirmation message
else else
s --> v : trip full
deactivate s
v --> a :trip full message 
deactivate v
end
deactivate a
@enduml