@startuml makeExcuse

title Make Excuse
actor Driver as a
participant View as v
participant Service as s
participant "Data Access" as da
database Database as db

activate a
a ->> v: Make an excuse
activate v
v--> a : Excuse form
a ->> v: Fill the Excuse form
v -> s: Send request
activate s
s -> da: Send Excuse model
activate da
da -> db: Add Excuse to database
activate db
db --> da: Confirm
deactivate db
da --> s
deactivate da
s --> v
deactivate s
v --> a: Show confirmation message
deactivate v
deactivate a


@enduml