@startuml modify-booking


actor Passenger as a
participant View as v
participant Service as s
participant "Data Access" as da
database Database as db

activate a
a ->> v: Show my bookings
activate v
a ->> v: Choose booking
v -> s: Get chosen booking
activate s
s -> da: Get chosen booking
activate da
da -> db: Get chosen booking from database
activate db
db --> da: Return booking
da --> s: Return booking
s --> v: Return booking
v --> a: Display booking
a ->> v: Edit the required details (Bus, Seat number)
v -> s: Send request
s -> da: Get trip information
da -> db: Get trip information
db --> da: Return trip information
deactivate db
da --> s: Return trip information
s -> s: Compare and check if modifications are allowed
deactivate da
alt modifications are allowed
    s --> v: Confirm
    v --> a: Show confirmation message
else modifications are not allowed
    s --> v: Modifications rejected
    deactivate s
    v --> a: Show rejection message
deactivate v
deactivate a
end


@enduml
