@startuml modify-booking


actor Passenger as a
participant View as v
participant Service as s
participant "Data Access" as da
database Database as db

activate a
a ->> v: Show my bookings
activate v
a ->> v: Choose booking
v -> s: Get chosen booking
activate s
s -> da: Get chosen booking
activate da
da -> db: Get chosen booking from database
activate db
db --> da: Return booking
da --> s: Return booking
s --> v: Return booking
v --> a: Display booking
a ->> v: Edit the required details (Bus, Seat number)
v -> s: Send modified booking model
s -> da: Update booking
da -> db: Update booking in database
db --> da: Confirm
deactivate db
da --> s: Confirm
deactivate da
s --> v: Confirm
deactivate s
v --> a: Show confirmation message
deactivate v
deactivate a


@enduml
