@startuml modify-booking


actor Passenger as a
participant View as v
participant Service as s
participant "Data Access" as da
database Database as db

activate a
a ->> v: Show my bookings
activate v
a ->> v: Choose booking
v -> s: Get chosen booking
activate s
s -> da
activate da
da -> db
activate db
db --> da
da --> s
s --> v
v --> a: Display chosen booking
a ->> v: Edit the required details (Bus, Seat number)
v -> s: Send modified booking model
s -> da: Update booking
da -> db: Update booking in database
db --> da: Confirm
deactivate db
da --> s
deactivate da
s --> v
deactivate s
v --> a: Show confirmation message
deactivate v
deactivate a


@enduml
