POST http://baas-gp.herokuapp.com/api/organization/paths HTTP/1.1
Content-Type: application/json
Authorization: Bearer 5|RXpaiT5By1H7kD4dYfyrwU9jknWcx05MlK8AerXo

{
  "route_id": 8,
  "path": {
    "path_name": "noooo",
    "stops": [
      {
        "name": "stop",
        "latitude": 30.034191242411794,
        "longitude": 31.219115845849345
      },
      {
        "name": "stop2",
        "latitude": 30.034121242411794,
        "longitude": 31.219145845849345
      }
    ]
  }
}