@startuml create-route


actor Organization as a
participant View as v
participant Service as s
participant "Data Access" as da
database Database as db

activate a
a ->> v: Create route
activate v
a ->> v: Enter a name for the route
a ->> v: Specify using a map the route start and destination
v -> s: Send request
activate s
s -> da: Send route model
activate da
da -> db: Add model to database
activate db
db --> da: Confirm
deactivate db
da --> s
deactivate da
s --> v
deactivate s
v --> a: Show confirmation message
deactivate v
deactivate a


@enduml
